export default {
  login: "t3dotgg",
  id: 6751787,
  node_id: "MDQ6VXNlcjY3NTE3ODc=",
  avatar_url: "https://avatars.githubusercontent.com/u/6751787?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/t3dotgg",
  html_url: "https://github.com/t3dotgg",
  followers_url: "https://api.github.com/users/t3dotgg/followers",
  following_url: "https://api.github.com/users/t3dotgg/following{/other_user}",
  gists_url: "https://api.github.com/users/t3dotgg/gists{/gist_id}",
  starred_url: "https://api.github.com/users/t3dotgg/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/t3dotgg/subscriptions",
  organizations_url: "https://api.github.com/users/t3dotgg/orgs",
  repos_url: "https://api.github.com/users/t3dotgg/repos",
  events_url: "https://api.github.com/users/t3dotgg/events{/privacy}",
  received_events_url: "https://api.github.com/users/t3dotgg/received_events",
  type: "User",
  site_admin: false,
  name: "Theo Browne",
  company: "CEO @ Ping.gg",
  blog: "t3.gg",
  location: "San Francisco, CA",
  email: null,
  hireable: true,
  bio: "I'm just here for the vibes, man",
  twitter_username: "t3dotgg",
  public_repos: 67,
  public_gists: 8,
  followers: 3474,
  following: 33,
  created_at: "2014-02-21T21:06:44Z",
  updated_at: "2022-11-30T09:02:08Z",
};
